name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish addon
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --all \
            --target unbound \
            --docker-hub ${{ secrets.DOCKER_USERNAME }} \
            --docker-password ${{ secrets.DOCKER_PASSWORD }}